✔ |  OK F W S | Context

⠏ |   0       | Backtraces
⠋ |   0 1     | Backtraces
⠙ |   0 2     | Backtraces
⠹ |   0 3     | Backtraces
⠸ |   0 4     | Backtraces
⠼ |   0 5     | Backtraces
✖ |   0 5     | Backtraces
────────────────────────────────────────────────────────────────────────────────
backtraces.R:6: error: errors thrown at block level are entraced
foo
Backtrace:
 1. f()
 2. g()

backtraces.R:11: error: errors thrown from a quasi-labelled argument are entraced
foo
Backtrace:
 1. testthat::expect_is(foo(), "foo")
 4. foo()

backtraces.R:18: error: errors thrown from a quasi-labelled argument are entraced (deep case)
foo
Backtrace:
 1. testthat::expect_is(f(), "foo")
 4. f()
 5. g()
 9. foo()

backtraces.R:28: error: errors thrown from a quasi-labelled argument are entraced (deep deep case)
foobar
Backtrace:
 1. f()
 2. g()
 6. foo()
 7. bar()

backtraces.R:34: failure: failed expect_error() prints a backtrace
`f()` threw an error with unexpected message.
Expected match: "foo"
Actual message: "bar"
Backtrace:
 1. testthat::expect_error(f(), "foo")
 6. f()
 7. g()
────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════
OK:       0
Failed:   5
Warnings: 0
Skipped:  0
