Test succeeded
Test succeeded
Failure (line 12): Failure has been forced

Failure (line 16): Failure has been forced

Failure (line 19): FALSE isn't true.

Failure (line 24): `i` not equal to 2.
1/1 mismatches
[1] 1 - 2 == -1

Error (line 33): Error: stop

Error (line 47): Error: !
Backtrace:
 1. f()
 2. g()
 3. h()

Error (line 56): Error: This is deep
Backtrace:
  1. f(25)
  2. f(x - 1)
  3. f(x - 1)
  4. f(x - 1)
  5. f(x - 1)
  6. f(x - 1)
  7. f(x - 1)
  8. f(x - 1)
  9. f(x - 1)
 10. f(x - 1)
     ...
 17. f(x - 1)
 18. f(x - 1)
 19. f(x - 1)
 20. f(x - 1)
 21. f(x - 1)
 22. f(x - 1)
 23. f(x - 1)
 24. f(x - 1)
 25. f(x - 1)
 26. f(x - 1)

Skip (line 62): Reason: skip

Skip (line 69): Reason: skip

Skip (line 72): Reason: empty test

Warning (line 78): abc

Warning (line 84): def

Warning (line 85): ghi
Backtrace:
 1. f()

Test succeeded
Error (line 111): Error: Throwable

