1..22
ok 1 Success
# Context Expectations
ok 2 Success
not ok 3 Failure:1
  Failure has been forced
not ok 4 Failure:2a
  Failure has been forced
not ok 5 Failure:2b
  FALSE isn't true.
not ok 6 Failure:loop
  `i` not equal to 2.
  1/1 mismatches
  [1] 1 - 2 == -1
ok 7 Failure:loop
# Context Errors
not ok 8 Error:1
  Message: stop
  Backtrace:
   1. NULL
   2. base::eval(code, test_env)
not ok 9 Error:3
  Message: !
  Backtrace:
   1. f()
   2. g()
   3. h()
# Context Recursion
not ok 10 Recursion:1
  Message: This is deep
  Backtrace:
    1. f(25)
    2. f(x - 1)
    3. f(x - 1)
    4. f(x - 1)
    5. f(x - 1)
    6. f(x - 1)
    7. f(x - 1)
    8. f(x - 1)
    9. f(x - 1)
   10. f(x - 1)
   11. f(x - 1)
   12. f(x - 1)
   13. f(x - 1)
   14. f(x - 1)
   15. f(x - 1)
   16. f(x - 1)
   17. f(x - 1)
   18. f(x - 1)
   19. f(x - 1)
   20. f(x - 1)
   21. f(x - 1)
   22. f(x - 1)
   23. f(x - 1)
   24. f(x - 1)
   25. f(x - 1)
   26. f(x - 1)
# Context Skips
ok 11 # SKIP Reason: skip
ok 12 # SKIP Reason: skip
ok 13 # SKIP Reason: empty test
# Context Warnings
ok 14 # WARNING abc
ok 15 # WARNING def
ok 16 # WARNING ghi
# Context Output
ok 17 Output:1
ok 18 Output:1
# Context Backtraces
not ok 19 errors thrown at block level are entraced
  Message: foo
  Backtrace:
   1. f()
   2. g()
not ok 20 errors thrown from a quasi-labelled argument are entraced
  Message: foo
  Backtrace:
   1. testthat::expect_is(foo(), "foo")
   4. foo()
not ok 21 errors thrown from a quasi-labelled argument are entraced (deep case)
  Message: foo
  Backtrace:
   1. testthat::expect_is(f(), "foo")
   4. f()
   5. g()
   9. foo()
not ok 22 errors thrown from a quasi-labelled argument are entraced (deep deep case)
  Message: foobar
  Backtrace:
   1. f()
   2. g()
   6. foo()
   7. bar()
